### ISSUE TITLE
ImportError: No module named pexpect

### ISSUE THREAD

**Issue by hcu5555** [scu-igroup/telnet-scanner#6]
hu@hu-VirtualBox:/home/newdisk/telnet-scanner$ python scanner.py 
Traceback (most recent call last):
  File "scanner.py", line 15, in <module>
    from new_module import *
  File "/home/newdisk/telnet-scanner/new_module.py", line 4, in <module>
    import pexpect
ImportError: No module named pexpect

**Comment by hcu5555** [comment]
Python 2.7
Ubuntu 16.04 LTS

**Comment by JTD420** [comment]
`sudo yum install pexpect`

You'll have an issue afterwards with the MySQLdb module missing but I can't help with that unfortunately.
